version: "3"

services:
  smartdns:
    image: pymumu/smartdns:latest
    container_name: smartdns
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./smartdns:/etc/smartdns
  dnsmasq:
    image: programster/dnsmasq
    container_name: dnsmasq
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.d:/etc/dnsmasq.d
      - ./hosts:/etc/hosts